apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  sources:
  - repoURL: https://helm.irsigler.cloud
    chart: uptime-kuma
    targetRevision: 2.14.2
    helm:
      valueFiles:
        - $values/Week6-ArgoCD/02_Uptime/values.yaml
  - repoURL: 'https://github.com/StijnPaepe/Cloud-Operations-Oefeningen.git'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma-app
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true