ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
  hosts:
    - host: up.75.co.ucll.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: uptime-kuma-tls
      hosts:
        - up.75.co.ucll.cloud