ingress:
  enabled: true
  hosts:
    - host: support.75.co.ucll.cloud
      paths:
        - path: /
          pathType: Prefix

redmineUsername: admin
redminePassword: password

databaseType: postgresql
mariadb:
  enabled: false
postgresql:
  enabled: true
  postgresqlDatabase: redmine
  postgresqlUsername: redmine
  postgresqlPassword: password