ingress:
  enabled: true
  certManager: true
  hostname: support.75.co.ucll.cloud
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cluster-issuer
    
redmineUsername: admin
redminePassword: password

databaseType: postgresql
mariadb:
  enabled: false
postgresql:
  enabled: true
  postgresqlDatabase: redmine
  postgresqlUsername: redmine
  postgresqlPassword: password