redmineUsername: admin
redminePassword: password

databaseType: postgresql
mariadb:
  enabled: false
postgresql:
  enabled: true
  auth:
    postgresqlUsername: username
    postgresqlPassword: password