apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-js
  namespace: argocd
spec:
  sources:
  - repoURL: https://charts.js.wiki
    chart: wiki
    targetRevision: x
    helm:
      valueFiles:
        - $values/Week6-ArgoCD/01_Wiki/values.yaml
  - repoURL: 'https://github.com/StijnPaepe/Cloud-Operations-Oefeningen.git'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wiki-js-app
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true